using System.Collections.Generic;
using System.Text;

namespace SourceSerializer.Generator
{
    internal static class BlockEmitter
    {
        public static string EmitAll(List<EmitEntry> structs, Dictionary<string, List<string>>? interfaceMap = null)
        {
            var iMap = interfaceMap ?? new Dictionary<string, List<string>>();
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
            sb.AppendLine("using System.Text;");
            sb.AppendLine();
            sb.AppendLine("namespace SourceSerializer");
            sb.AppendLine("{");
            sb.AppendLine("    partial class SerializerBlocks");
            sb.AppendLine("    {");

            bool hasAny = structs.Count > 0 || iMap.Count > 0;
            if (hasAny)
            {
                sb.AppendLine("        [ExcludeFromCodeCoverage]");
                sb.AppendLine("        static SerializerBlocks()");
                sb.AppendLine("        {");
                foreach (var e in structs)
                {
                    string blockName = BlockName(e.Common.StructName);
                    sb.AppendLine($"            Store<{e.Common.StructName}>(new {blockName}());");
                }
                foreach (var ifaceName in iMap.Keys)
                {
                    string blockName = BlockName(ifaceName);
                    sb.AppendLine($"            Store<{ifaceName}>(new {blockName}());");
                }
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            foreach (var e in structs)
            {
                EmitBlock(sb, e.Common.StructName, false);
            }
            foreach (var ifaceName in iMap.Keys)
            {
                EmitBlock(sb, ifaceName, true);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string BlockName(string typeName)
            => "Block_" + EmitHelpers.GetMethodName("Scan", typeName).Substring(5);

        private static void EmitBlock(StringBuilder sb, string typeName, bool isInterface)
        {
            string blockName = BlockName(typeName);
            string scanMethod = EmitHelpers.GetMethodName("Scan", typeName);
            string emitMethod = EmitHelpers.GetMethodName("Emit", typeName);

            sb.AppendLine("        [ExcludeFromCodeCoverage]");
            sb.AppendLine($"        readonly struct {blockName} : ISerializerBlock<{typeName}>");
            sb.AppendLine("        {");
            sb.AppendLine($"            public int Scan(ReadOnlySpan<char> text, int pos, out {typeName} value)");
            sb.AppendLine("            {");
            sb.AppendLine($"                int r = SerializerBlocks.{scanMethod}(text, pos, out value);");
            sb.AppendLine("                return r;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine($"            public void Emit(StringBuilder sb, {typeName} value)");
            sb.AppendLine("            {");
            sb.AppendLine($"                SerializerBlocks.{emitMethod}(sb, value);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
    }
}
