using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;

namespace SourceSerializer.Generator
{
    /// <summary>
    /// 发射策略：控制字段赋值模式（逐字段 vs 构造器）。
    /// </summary>
    internal readonly struct EmitStrategy
    {
        private readonly bool _useConstructor;
        public EmitStrategy(bool useConstructor) => _useConstructor = useConstructor;
        public bool UseConstructor => _useConstructor;
        public string AssignTarget(string fieldName) =>
            _useConstructor ? $"__f_{fieldName}" : $"value.@{fieldName}";
        public string RepetitionTargetPrefix => _useConstructor ? "__f_" : "value.@";
    }

    /// <summary>
    /// 发射器入口：封装一个待生成代码的结构体/类。
    /// </summary>
    internal struct EmitEntry
    {
        public TemplateCommon Common;
        public List<TemplateNode> Nodes;
        public Dictionary<string, FieldInfo> FieldTypes;
    }

    /// <summary>
    /// 将模板 AST 编译为 C# span scanner 源代码。
    /// 生成代码注入到 internal static partial class SerializerBlocks。
    /// </summary>
    // 纯编译期代码发射器，运行时从不实例化
    [ExcludeFromCodeCoverage]
    internal static class CodeEmitter
    {
        // ═══════════════════════════════════════════════════════
        // 常量
        // ═══════════════════════════════════════════════════════

        /// <summary>顶层方法体单层缩进（12 空格 = 3 层嵌套: class > method > body）</summary>
        private const string IndentTop = "            ";

        /// <summary>子块额外缩进（4 空格）</summary>
        private const string IndentStep = "    ";

        // ═══════════════════════════════════════════════════════
        // 发射计数器 — 每次 EmitAll 重置，确保增量生成输出稳定
        // ═══════════════════════════════════════════════════════

        private static int _optCounter;
        private static Dictionary<string, string> _scanVarMap = new(StringComparer.Ordinal);

        // ═══════════════════════════════════════════════════════
        // 主入口
        // ═══════════════════════════════════════════════════════

        public static string EmitAll(
            List<EmitEntry> structs,
            Dictionary<string, string> dependencyGraph,
            Dictionary<string, string>? typeAliases = null,
            Dictionary<string, List<(string MemberName, string Tag)>>? enumTagMap = null,
            Dictionary<string, List<string>>? interfaceMap = null)
        {
            var tAliases = typeAliases ?? new Dictionary<string, string>();
            var eTags = enumTagMap ?? new Dictionary<string, List<(string, string)>>(StringComparer.Ordinal);
            var iMap = interfaceMap ?? new Dictionary<string, List<string>>(StringComparer.Ordinal);

            // 每次 EmitAll 重置所有计数器，确保增量生成输出稳定
            EmitHelpers.ResetCounters();
            _optCounter = 0;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable CS0162");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine();
            sb.AppendLine("namespace SourceSerializer");
            sb.AppendLine("{");
            sb.AppendLine("    partial class SerializerBlocks");
            sb.AppendLine("    {");

            foreach (var e in structs)
            {
                sb.Append(EmitMethod(e.Common.StructName, e.Nodes, e.Common.NeedsHeapAlloc, e.Common.IsCollection, e.Common.MatchedCtorParams, dependencyGraph, tAliases, eTags, e.FieldTypes));
                sb.AppendLine();
            }

            foreach (var kv in eTags)
            {
                sb.Append(EmitEnumTagMethod(kv.Key, kv.Value));
                sb.AppendLine();
            }

            // 接口 dispatch 方法
            foreach (var kv in iMap)
            {
                sb.Append(EmitInterfaceDispatch(kv.Key, kv.Value, dependencyGraph));
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// 为接口生成 dispatch 扫描方法：尝试全部实现，选推进最远的（长前缀匹配胜出）。
        /// </summary>
        private static string EmitInterfaceDispatch(string ifaceName, List<string> concreteTypes,
            Dictionary<string, string> dependencyGraph)
        {
            var sb = new StringBuilder();
            string methodName = EmitHelpers.GetMethodName("Scan",ifaceName);
            string bestVar = EmitHelpers.GetUniqueVar("best");
            string bestValueVar = EmitHelpers.GetUniqueVar("bestVal");

            sb.AppendLine($"        /// <summary>接口分发扫描器：{ifaceName}</summary>");
            sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"        internal static int {methodName}(ReadOnlySpan<char> src, int pos, out {ifaceName} value)");
            sb.AppendLine("        {");
            sb.AppendLine("            value = default;");
            sb.AppendLine("            if (pos >= src.Length) return pos;");
            sb.AppendLine("            int start = pos;");
            sb.AppendLine($"            int {bestVar} = pos;");
            sb.AppendLine($"            {ifaceName} {bestValueVar} = default;");
            sb.AppendLine();

            for (int i = 0; i < concreteTypes.Count; i++)
            {
                string concrete = concreteTypes[i];
                string scanMethod = dependencyGraph.TryGetValue(concrete, out var m)
                    ? m : EmitHelpers.GetMethodName("Scan",concrete);
                string localVar = EmitHelpers.GetUniqueVar(concrete);
                string rVar = EmitHelpers.GetUniqueVar("r");

                sb.AppendLine($"            // try {concrete}");
                sb.AppendLine($"            int {rVar} = {scanMethod}(src, pos, out {concrete} {localVar});");
                sb.AppendLine($"            if ({rVar} > {bestVar}) {{ {bestVar} = {rVar}; {bestValueVar} = {localVar}; }}");
                sb.AppendLine();
            }

            sb.AppendLine($"            if ({bestVar} > pos) {{ value = {bestValueVar}; return {bestVar}; }}");
            sb.AppendLine("            return start;");
            sb.AppendLine("        }");

            return sb.ToString();
        }

        private static string EmitMethod(
            string structTypeName, List<TemplateNode> nodes, bool needsHeapAlloc, bool isCollection,
            string[]? matchedCtorParams,
            Dictionary<string, string> dependencyGraph,
            Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes)
        {
            var sb = new StringBuilder();
            string methodName = EmitHelpers.GetMethodName("Scan",structTypeName);
            // 只有构造器路径才需要延迟构造。readonly struct 无构造器由 GenerateSource 拦截。
            var strategy = new EmitStrategy(matchedCtorParams != null);

            sb.AppendLine($"        /// <summary>字面量扫描器：{structTypeName}</summary>");
            sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"        internal static int {methodName}(ReadOnlySpan<char> src, int pos, out {structTypeName} value)");
            sb.AppendLine("        {");

            if (strategy.UseConstructor)
            {
                sb.AppendLine("            value = default;");
                _scanVarMap.Clear();
            }
            else
            {
                if (needsHeapAlloc)
                    sb.AppendLine($"            value = new {structTypeName}();");
                else
                    sb.AppendLine("            value = default;");

                // 初始化集合字段为空集合（仅对用户 struct，不处理 synthetic collection 类型）
                if (!isCollection)
                {
                    foreach (var kv in fieldTypes)
                    {
                        if (kv.Value.Kind == CollectionKind.Sequential)
                            sb.AppendLine($"            value.{kv.Key} = {ResolveCollectionType(kv.Value.TypeName, kv.Value.ElemType!)}();");
                        else if (kv.Value.Kind == CollectionKind.Array)
                            sb.AppendLine($"            value.{kv.Key} = System.Array.Empty<{kv.Value.ElemType}>();");
                    }
                }
            }

            sb.AppendLine("            if (pos >= src.Length) return pos;");
            sb.AppendLine("            int start = pos;");
            sb.AppendLine();

            // 顶层 failure mode: 直接 return start
            EmitNodeList(sb, nodes, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, IndentTop, failureLabel: null, isInRepetition: false, isCollection: isCollection, strategy: strategy);

            if (strategy.UseConstructor)
            {
                sb.AppendLine();
                var args = string.Join(", ", matchedCtorParams!.Select(p =>
                {
                    var fld = fieldTypes.Keys.FirstOrDefault(k =>
                        string.Equals(k, p, StringComparison.OrdinalIgnoreCase));
                    return fld != null && _scanVarMap.TryGetValue(fld, out var sv) ? sv : "default";
                }));
                sb.AppendLine($"            value = new {structTypeName}({args});");
            }

            sb.AppendLine();
            sb.AppendLine("            return pos;");
            sb.AppendLine("        }");

            return sb.ToString();
        }

        /// <param name="failureLabel">
        /// 失败跳转标签。null 表示顶层（使用 return start），非 null 表示在可选块内（使用 goto failureLabel）
        /// </param>
        private static void EmitNodeList(
            StringBuilder sb, List<TemplateNode> nodes, string structTypeName,
            Dictionary<string, string> dependencyGraph, Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes,
            string indent, string? failureLabel, bool isInRepetition, bool isCollection = false,
            EmitStrategy strategy = default)
        {
            for (int i = 0; i < nodes.Count; i++)
            {
                EmitNode(sb, nodes[i], structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, indent, failureLabel, isInRepetition, isCollection, strategy);
            }
        }

        private static void EmitNode(
            StringBuilder sb, TemplateNode node, string structTypeName,
            Dictionary<string, string> dependencyGraph, Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes,
            string indent, string? failureLabel, bool isInRepetition, bool isCollection = false,
            EmitStrategy strategy = default)
        {
            switch (node)
            {
                case LiteralTextNode lit:
                    EmitLiteralText(sb, lit, indent, failureLabel);
                    break;
                case FieldDirectiveNode field:
                    EmitFieldDirective(sb, field, indent, dependencyGraph, typeAliases, enumTags, fieldTypes, failureLabel, isInRepetition, isCollection, strategy);
                    break;
                case OptionalBlockNode opt:
                    EmitOptionalBlock(sb, opt, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, indent, isCollection, strategy);
                    break;
                case RepetitionNode rep:
                    EmitRepetitionBlock(sb, rep, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, indent, isCollection, strategy);
                    break;
            }
        }

        private static string MakeFailure(string? failureLabel)
        {
            return failureLabel != null
                ? $"goto {failureLabel};"
                : "return start;";
        }

        // ── 裸文字 ────────────────────────────────────

        private static void EmitLiteralText(StringBuilder sb, LiteralTextNode lit, string indent, string? failureLabel)
        {
            string text = lit.Text;
            if (text.Length == 0) return;
            string fail = MakeFailure(failureLabel);

            sb.AppendLine($"{indent}// literal: {EscapeForComment(text)}");
            sb.AppendLine($"{indent}if (pos + {text.Length} > src.Length) {fail}");

            for (int i = 0; i < text.Length; i++)
            {
                char c = text[i];
                string cLit = c == '\'' ? @"'\''" : $"'{c}'";
                sb.AppendLine($"{indent}if (src[pos + {i}] != {cLit}) {fail}");
            }

            sb.AppendLine($"{indent}pos += {text.Length};");
            sb.AppendLine();
        }

        // ── 字段指令 ──────────────────────────────────

        private static void EmitFieldDirective(
            StringBuilder sb, FieldDirectiveNode field, string indent,
            Dictionary<string, string> dependencyGraph, Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes,
            string? failureLabel, bool isInRepetition, bool structIsCollection = false,
            EmitStrategy strategy = default)
        {
            string typeAlias = field.TypeAlias;
            string fieldName = field.FieldName;
            string localVar = EmitHelpers.GetUniqueVar(fieldName);
            string fail = MakeFailure(failureLabel);

            // 别名映射：用户定义的名称 → 实际内置类型
            string resolvedType = typeAliases.TryGetValue(typeAlias, out var backing)
                ? backing : typeAlias;

            // 决定赋值目标: repetition 内的集合字段走数组缓存索引，否则直接写 value.Field
            fieldTypes.TryGetValue(fieldName, out var ft);
            bool isCollection = ft.Kind != CollectionKind.None;
            bool useBuffer = isInRepetition && isCollection;

            // 构造器路径：记录扫描变量名，跳过中间赋值，末尾直接用扫描变量构造
            bool skipAssign = strategy.UseConstructor && !useBuffer && !structIsCollection;
            if (skipAssign) _scanVarMap[fieldName] = localVar;

            string assignTarget;
            if (useBuffer)
                assignTarget = $"__buf_{fieldName}[__cnt_{fieldName}]";
            else if (structIsCollection)
                assignTarget = "value";
            else
                assignTarget = strategy.AssignTarget(fieldName);
            string assignOp = structIsCollection && !useBuffer
                ? $".Add"
                : " =";
            string assignSuffix = structIsCollection && !useBuffer
                ? $"({localVar});"
                : $" {localVar};";

            // 缓存数组扩容逻辑: 16 → ×4 → 1024 后 ×2
            string bufferResize = useBuffer
                ? $"{indent}if (__cnt_{fieldName} >= __buf_{fieldName}.Length)\n{indent}{{\n{indent}    int __ns_{fieldName} = __buf_{fieldName}.Length < 1024 ? __buf_{fieldName}.Length * 4 : __buf_{fieldName}.Length * 2;\n{indent}    var __tmp_{fieldName} = new {ft.ElemType}[__ns_{fieldName}];\n{indent}    Array.Copy(__buf_{fieldName}, __tmp_{fieldName}, __cnt_{fieldName});\n{indent}    __buf_{fieldName} = __tmp_{fieldName};\n{indent}}}\n"
                : "";
            string bufferIncrement = useBuffer
                ? $"{indent}__cnt_{fieldName}++;"
                : "";

            if (BuiltinTypeNames.All.Contains(resolvedType))
            {
                string scannerMethod = $"Scan_{char.ToUpperInvariant(resolvedType[0])}{resolvedType.Substring(1)}";
                string csharpType = resolvedType.ToLowerInvariant();
                string aliasNote = resolvedType != typeAlias ? $" (alias→{resolvedType})" : "";
                string preVar = EmitHelpers.GetUniqueVar("pre");

                sb.AppendLine($"{indent}// <{typeAlias} {fieldName}>{aliasNote}");
                if (useBuffer) sb.AppendLine(bufferResize);
                sb.AppendLine($"{indent}int {preVar} = pos;");
                sb.AppendLine($"{indent}pos = SerializerRegistry.{scannerMethod}(src, pos, out {csharpType} {localVar});");
                sb.AppendLine(isCollection
                    ? $"{indent}// (collection — empty is valid)"
                    : $"{indent}if (pos == {preVar}) {fail}");
                if (!skipAssign) sb.AppendLine($"{indent}{assignTarget}{assignOp}{assignSuffix}");
                if (useBuffer) sb.AppendLine(bufferIncrement);
            }
            else if (enumTags.TryGetValue(typeAlias, out var tags))
            {
                string preVar = EmitHelpers.GetUniqueVar("pre");
                sb.AppendLine($"{indent}// <{typeAlias} {fieldName}> (enum tag)");
                if (useBuffer) sb.AppendLine(bufferResize);
                sb.AppendLine($"{indent}int {preVar} = pos;");
                sb.AppendLine($"{indent}pos = Scan_Enum_{typeAlias}(src, pos, out {typeAlias} {localVar});");
                sb.AppendLine($"{indent}if (pos == {preVar}) {fail}");
                if (!skipAssign) sb.AppendLine($"{indent}{assignTarget}{assignOp}{assignSuffix}");
                if (useBuffer) sb.AppendLine(bufferIncrement);
            }
            else
            {
                if (dependencyGraph.TryGetValue(typeAlias, out string depMethod))
                {
                    string preVar = EmitHelpers.GetUniqueVar("pre");
                    sb.AppendLine($"{indent}// <{typeAlias} {fieldName}> (nested)");
                    if (useBuffer) sb.AppendLine(bufferResize);
                    sb.AppendLine($"{indent}int {preVar} = pos;");
                    sb.AppendLine($"{indent}pos = {depMethod}(src, pos, out {typeAlias} {localVar});");
                    sb.AppendLine(isCollection
                        ? $"{indent}// (collection — empty is valid)"
                        : $"{indent}if (pos == {preVar}) {fail}");
                    if (!skipAssign) sb.AppendLine($"{indent}{assignTarget}{assignOp}{assignSuffix}");
                    if (useBuffer) sb.AppendLine(bufferIncrement);
                }
                else
                {
                    sb.AppendLine($"{indent}// ERROR: unregistered type '{typeAlias}'");
                }
            }
            sb.AppendLine();
        }

        // ── 枚举标签扫描方法 ──────────────────────────

        private static string EmitEnumTagMethod(string enumName, List<(string MemberName, string Tag)> tags)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"        /// <summary>枚举标签扫描器：{enumName}</summary>");
            sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"        internal static int Scan_Enum_{enumName}(ReadOnlySpan<char> src, int pos, out {enumName} value)");
            sb.AppendLine("        {");
            sb.AppendLine("            value = default;");
            sb.AppendLine("            if (pos >= src.Length) return pos;");
            sb.AppendLine("            int start = pos;");
            sb.AppendLine("            while (pos < src.Length && char.IsLetter(src[pos])) pos++;");
            sb.AppendLine("            if (pos == start) return start;");
            sb.AppendLine("            switch (new string(src.Slice(start, pos - start)))");
            sb.AppendLine("            {");
            foreach (var (member, tag) in tags)
                sb.AppendLine($"                case \"{tag}\": value = {enumName}.{member}; break;");
            sb.AppendLine("                default: return start;");
            sb.AppendLine("            }");
            sb.AppendLine("            return pos;");
            sb.AppendLine("        }");
            return sb.ToString();
        }

        // ── 重复块 ────────────────────────────────────

        private static void EmitRepetitionBlock(
            StringBuilder sb, RepetitionNode rep, string structTypeName,
            Dictionary<string, string> dependencyGraph, Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes,
            string indent, bool isCollection = false, EmitStrategy strategy = default)
        {
            if (rep.Body.Count == 0) return;

            int id = EmitHelpers.NextRepId();
            string failLabel = $"repFail_{id}";
            string innerIndent = indent + IndentStep;

            // ── 收集 repetition body 内的集合字段 ──
            var bodyNodes = rep.First != null ? rep.First.Concat(rep.Body).ToList() : rep.Body;
            var collectionFields = FindCollectionFields(bodyNodes, fieldTypes);

            sb.AppendLine($"{indent}// <repetition>");

            // ── 循环前: 声明缓存数组 ──
            foreach (var (fieldName, elemType) in collectionFields)
            {
                sb.AppendLine($"{indent}var __buf_{fieldName} = new {elemType}[16];");
                sb.AppendLine($"{indent}int __cnt_{fieldName} = 0;");
            }

            if (rep.First != null)
            {
                string savedVar = $"saved_{id}";
                string firstFail = $"repFirstFail_{id}";

                // ── <first>: 首个元素（无分隔符）──
                sb.AppendLine($"{indent}// <first> — try first element (no separator)");
                sb.AppendLine($"{indent}int {savedVar} = pos;");
                sb.AppendLine($"{indent}{{");
                EmitNodeList(sb, rep.First, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, innerIndent, firstFail, isInRepetition: true, isCollection: isCollection);
                sb.AppendLine($"{innerIndent}goto repLoop_{id};");
                sb.AppendLine($"{indent}}}");
                sb.AppendLine($"{indent}{firstFail}:");
                sb.AppendLine($"{innerIndent}pos = {savedVar};");
                sb.AppendLine($"{innerIndent}goto repEnd_{id};");

                // ── <body>: 后续元素（含分隔符）──
                sb.AppendLine($"{indent}repLoop_{id}: // <body> — subsequent elements");
                sb.AppendLine($"{indent}while (true)");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{innerIndent}{savedVar} = pos;");
                EmitNodeList(sb, rep.Body, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, innerIndent, failLabel, isInRepetition: true, isCollection: isCollection);
                sb.AppendLine($"{innerIndent}continue;");
                sb.AppendLine($"{innerIndent}{failLabel}:");
                sb.AppendLine($"{innerIndent}    pos = saved_{id};");
                sb.AppendLine($"{innerIndent}    break;");
                sb.AppendLine($"{indent}}}");
                sb.AppendLine($"{indent}repEnd_{id}: ;");
            }
            else
            {
                // 向后兼容: 无 <first>/<body>，整个 body 作为通用循环模式
                sb.AppendLine($"{indent}while (true)");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{innerIndent}int saved_{id} = pos;");
                EmitNodeList(sb, rep.Body, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, innerIndent, failLabel, isInRepetition: true, isCollection: isCollection);
                sb.AppendLine($"{innerIndent}continue;");
                sb.AppendLine($"{innerIndent}{failLabel}:");
                sb.AppendLine($"{innerIndent}    pos = saved_{id};");
                sb.AppendLine($"{innerIndent}    break;");
                sb.AppendLine($"{indent}}}");
            }

            // ── 循环后: 缓存数组 → 目标字段单次转换 ──
            string targetPrefix = strategy.RepetitionTargetPrefix;
            foreach (var (fieldName, elemType) in collectionFields)
            {
                var ft = fieldTypes[fieldName];
                if (ft.Kind == CollectionKind.Sequential)
                {
                    sb.AppendLine($"{indent}var __final_{fieldName} = new {elemType}[__cnt_{fieldName}];");
                    sb.AppendLine($"{indent}Array.Copy(__buf_{fieldName}, __final_{fieldName}, __cnt_{fieldName});");
                    sb.AppendLine($"{indent}{targetPrefix}{fieldName} = {ResolveCollectionType(ft.TypeName, elemType!)}(__final_{fieldName});");
                }
                else // Array
                {
                    sb.AppendLine($"{indent}var __final_{fieldName} = new {elemType}[__cnt_{fieldName}];");
                    sb.AppendLine($"{indent}Array.Copy(__buf_{fieldName}, __final_{fieldName}, __cnt_{fieldName});");
                    sb.AppendLine($"{indent}{targetPrefix}{fieldName} = __final_{fieldName};");
                }
            }

            sb.AppendLine($"{indent}// </repetition>");
            sb.AppendLine();
        }

        /// <summary>递归查找节点列表中的集合字段，返回 (fieldName, elementType)</summary>
        private static List<(string FieldName, string ElemType)> FindCollectionFields(
            List<TemplateNode> nodes,
            Dictionary<string, FieldInfo> fieldTypes)
        {
            var result = new List<(string, string)>();
            foreach (var node in nodes)
            {
                if (node is FieldDirectiveNode f)
                {
                    if (fieldTypes.TryGetValue(f.FieldName, out var ft)
                        && ft.Kind != CollectionKind.None
                        && ft.ElemType != null)
                    {
                        bool found = false;
                        for (int j = 0; j < result.Count; j++)
                            if (result[j].Item1 == f.FieldName) { found = true; break; }
                        if (!found)
                            result.Add((f.FieldName, ft.ElemType!));
                    }
                }
                else if (node is OptionalBlockNode opt)
                {
                    var nested = FindCollectionFields(opt.Body, fieldTypes);
                    for (int j = 0; j < nested.Count; j++) result.Add(nested[j]);
                }
                else if (node is RepetitionNode nestedRep)
                {
                    var nested = FindCollectionFields(nestedRep.Body, fieldTypes);
                    for (int j = 0; j < nested.Count; j++) result.Add(nested[j]);
                }
            }
            return result;
        }

        // ── 可选块 ────────────────────────────────────

        private static void EmitOptionalBlock(
            StringBuilder sb, OptionalBlockNode opt, string structTypeName,
            Dictionary<string, string> dependencyGraph, Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes,
            string indent, bool isCollection = false, EmitStrategy strategy = default)
        {
            int id = _optCounter++;
            string skipLabel = $"skipOpt_{id}";
            string endLabel = $"endOpt_{id}";
            string innerIndent = indent + IndentStep;

            sb.AppendLine($"{indent}// <optional>");
            sb.AppendLine($"{indent}int saved_{id} = pos;");
            sb.AppendLine($"{indent}{{");

            if (opt.Body.Count > 0 && opt.Body[0] is LiteralTextNode firstLit && firstLit.Text.Length <= 6)
            {
                // 有前置字面量：只在前缀匹配时才尝试 body
                string text = firstLit.Text;
                sb.Append($"{innerIndent}if (pos + {text.Length} <= src.Length");
                for (int i = 0; i < text.Length; i++)
                {
                    char c = text[i];
                    string cLit = c == '\'' ? @"'\''" : $"'{c}'";
                    sb.Append($" && src[pos + {i}] == {cLit}");
                }
                sb.AppendLine(")");
                sb.AppendLine($"{innerIndent}{{");
                sb.AppendLine($"{innerIndent}    pos += {text.Length};");
                var rest = GetRest(opt.Body, 1);
                if (rest.Count > 0)
                    EmitNodeList(sb, rest, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, innerIndent + IndentStep, skipLabel, isInRepetition: false, isCollection: isCollection, strategy: strategy);
                sb.AppendLine($"{innerIndent}    goto {endLabel};");
                sb.AppendLine($"{innerIndent}}}");
            }
            else
            {
                // 无前置字面量：直接尝试 body
                EmitNodeList(sb, opt.Body, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, innerIndent, skipLabel, isInRepetition: false, isCollection: isCollection, strategy: strategy);
                sb.AppendLine($"{innerIndent}goto {endLabel};");
            }

            sb.AppendLine($"{indent}}}");
            sb.AppendLine($"{indent}{skipLabel}:");
            sb.AppendLine($"{indent}    pos = saved_{id};");
            sb.AppendLine($"{indent}{endLabel}:");
            sb.AppendLine($"{indent}// </optional>");
            sb.AppendLine();
        }

        private static List<TemplateNode> GetRest(List<TemplateNode> list, int start)
        {
            var rest = new List<TemplateNode>();
            for (int i = start; i < list.Count; i++)
                rest.Add(list[i]);
            return rest;
        }

        // ── 辅助 ──────────────────────────────────────

        /// <summary>根据字段类型名选择合适的集合构造类型（List vs HashSet）。</summary>
        private static string ResolveCollectionType(string fieldTypeName, string elemType)
        {
            bool isSet = fieldTypeName.StartsWith("HashSet<") ||
                         fieldTypeName.StartsWith("System.Collections.Generic.HashSet<") ||
                         fieldTypeName.StartsWith("ISet<") ||
                         fieldTypeName.StartsWith("System.Collections.Generic.ISet<");
            string collType = isSet ? "System.Collections.Generic.HashSet" : "System.Collections.Generic.List";
            return $"new {collType}<{elemType}>";
        }

        private static string EscapeForComment(string text)
            => text.Replace("\n", "\\n").Replace("\r", "\\r");
    }
}
