using System;
using System.Collections.Generic;
using System.Text;

namespace SourceSerializer.Generator
{
    /// <summary>
    /// 将模板 AST 编译为 C# span scanner 源代码。
    /// 生成代码注入到 internal static partial class SerializerScanners。
    /// </summary>
    internal static class CodeEmitter
    {
        private static readonly HashSet<string> BuiltinTypes = new(StringComparer.OrdinalIgnoreCase)
        {
            "float", "double", "int", "uint", "long", "ulong",
            "short", "ushort", "byte", "sbyte", "bool", "char",
        };

        private static Dictionary<string, string> _typeAliases = new();
        private static Dictionary<string, List<(string MemberName, string Tag)>> _enumTags
            = new Dictionary<string, List<(string, string)>>(StringComparer.Ordinal);

        public static string EmitAll(
            List<(string StructName, List<TemplateNode> Nodes)> structs,
            Dictionary<string, string> dependencyGraph,
            Dictionary<string, string>? typeAliases = null,
            Dictionary<string, List<(string MemberName, string Tag)>>? enumTagMap = null)
        {
            _typeAliases = typeAliases ?? new Dictionary<string, string>();
            _enumTags = enumTagMap ?? new Dictionary<string, List<(string, string)>>(StringComparer.Ordinal);
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable CS0162");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine();
            sb.AppendLine("namespace SourceSerializer");
            sb.AppendLine("{");
            sb.AppendLine("    partial class SerializerScanners");
            sb.AppendLine("    {");

            if (structs.Count > 0)
            {
                sb.AppendLine("        static SerializerScanners()");
                sb.AppendLine("        {");
                foreach (var (name, _) in structs)
                {
                    string methodName = GetScannerMethodName(name);
                    sb.AppendLine($"            ScannerRegistry<{name}>.Scanner = (ReadOnlySpan<char> s, int p, out {name} v) =>");
                    sb.AppendLine($"            {{");
                    sb.AppendLine($"                int r = {methodName}(s, p, out v);");
                    sb.AppendLine($"                return r;");
                    sb.AppendLine($"            }};");
                }
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            _varCounter = 0;
            foreach (var (name, nodes) in structs)
            {
                sb.Append(EmitMethod(name, nodes, dependencyGraph));
                sb.AppendLine();
            }

            // 枚举标签扫描方法
            foreach (var kv in _enumTags)
            {
                sb.Append(EmitEnumTagMethod(kv.Key, kv.Value));
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string EmitMethod(
            string structTypeName, List<TemplateNode> nodes,
            Dictionary<string, string> dependencyGraph)
        {
            var sb = new StringBuilder();
            string methodName = GetScannerMethodName(structTypeName);

            sb.AppendLine($"        /// <summary>字面量扫描器：{structTypeName}</summary>");
            sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"        internal static int {methodName}(ReadOnlySpan<char> src, int pos, out {structTypeName} value)");
            sb.AppendLine("        {");
            sb.AppendLine("            value = default;");
            sb.AppendLine("            if (pos >= src.Length) return pos;");
            sb.AppendLine("            int start = pos;");
            sb.AppendLine();

            // 顶层 failure mode: 直接 return start
            EmitNodeList(sb, nodes, structTypeName, dependencyGraph, "            ", failureLabel: null);

            sb.AppendLine();
            sb.AppendLine("            return pos;");
            sb.AppendLine("        }");

            return sb.ToString();
        }

        /// <param name="failureLabel">
        /// 失败跳转标签。null 表示顶层（使用 return start），非 null 表示在可选块内（使用 goto failureLabel）
        /// </param>
        private static void EmitNodeList(
            StringBuilder sb, List<TemplateNode> nodes, string structTypeName,
            Dictionary<string, string> dependencyGraph, string indent, string? failureLabel)
        {
            for (int i = 0; i < nodes.Count; i++)
            {
                EmitNode(sb, nodes[i], structTypeName, dependencyGraph, indent, failureLabel);
            }
        }

        private static void EmitNode(
            StringBuilder sb, TemplateNode node, string structTypeName,
            Dictionary<string, string> dependencyGraph, string indent, string? failureLabel)
        {
            switch (node)
            {
                case LiteralTextNode lit:
                    EmitLiteralText(sb, lit, indent, failureLabel);
                    break;
                case FieldDirectiveNode field:
                    EmitFieldDirective(sb, field, indent, dependencyGraph, failureLabel);
                    break;
                case OptionalBlockNode opt:
                    EmitOptionalBlock(sb, opt, structTypeName, dependencyGraph, indent);
                    break;
                case RepetitionNode rep:
                    EmitRepetitionBlock(sb, rep, structTypeName, dependencyGraph, indent);
                    break;
            }
        }

        private static string MakeFailure(string? failureLabel)
        {
            return failureLabel != null
                ? $"goto {failureLabel};"
                : "return start;";
        }

        // ── 裸文字 ────────────────────────────────────

        private static void EmitLiteralText(StringBuilder sb, LiteralTextNode lit, string indent, string? failureLabel)
        {
            string text = lit.Text;
            if (text.Length == 0) return;
            string fail = MakeFailure(failureLabel);

            sb.AppendLine($"{indent}// literal: {EscapeForComment(text)}");
            sb.AppendLine($"{indent}if (pos + {text.Length} > src.Length) {fail}");

            for (int i = 0; i < text.Length; i++)
            {
                char c = text[i];
                string cLit = c == '\'' ? @"'\''" : $"'{c}'";
                sb.AppendLine($"{indent}if (src[pos + {i}] != {cLit}) {fail}");
            }

            sb.AppendLine($"{indent}pos += {text.Length};");
            sb.AppendLine();
        }

        // ── 字段指令 ──────────────────────────────────

        private static void EmitFieldDirective(
            StringBuilder sb, FieldDirectiveNode field, string indent,
            Dictionary<string, string> dependencyGraph, string? failureLabel)
        {
            string typeAlias = field.TypeAlias;
            string fieldName = field.FieldName;
            string localVar = GetUniqueVar(fieldName);
            string fail = MakeFailure(failureLabel);

            // 别名映射：用户定义的名称 → 实际内置类型
            string resolvedType = _typeAliases.TryGetValue(typeAlias, out var backing)
                ? backing : typeAlias;

            if (BuiltinTypes.Contains(resolvedType))
            {
                string scannerMethod = $"Scan_{char.ToUpperInvariant(resolvedType[0])}{resolvedType.Substring(1)}";
                string csharpType = resolvedType.ToLowerInvariant();
                string aliasNote = resolvedType != typeAlias ? $" (alias→{resolvedType})" : "";
                string preVar = GetUniqueVar("pre");

                sb.AppendLine($"{indent}// <{typeAlias} {fieldName}>{aliasNote}");
                sb.AppendLine($"{indent}int {preVar} = pos;");
                sb.AppendLine($"{indent}pos = SerializerRegistry.{scannerMethod}(src, pos, out {csharpType} {localVar});");
                sb.AppendLine($"{indent}if (pos == {preVar}) {fail}");
                sb.AppendLine($"{indent}value.{fieldName} = {localVar};");
            }
            else if (_enumTags.TryGetValue(typeAlias, out var tags))
            {
                // 枚举标签类型: 生成 switch-on-string 扫描
                string preVar = GetUniqueVar("pre");
                sb.AppendLine($"{indent}// <{typeAlias} {fieldName}> (enum tag)");
                sb.AppendLine($"{indent}int {preVar} = pos;");
                sb.AppendLine($"{indent}pos = Scan_Enum_{typeAlias}(src, pos, out {typeAlias} {localVar});");
                sb.AppendLine($"{indent}if (pos == {preVar}) {fail}");
                sb.AppendLine($"{indent}value.{fieldName} = {localVar};");
            }
            else
            {
                if (dependencyGraph.TryGetValue(typeAlias, out string depMethod))
                {
                    string preVar = GetUniqueVar("pre");
                    sb.AppendLine($"{indent}// <{typeAlias} {fieldName}> (nested)");
                    sb.AppendLine($"{indent}int {preVar} = pos;");
                    sb.AppendLine($"{indent}pos = {depMethod}(src, pos, out {typeAlias} {localVar});");
                    sb.AppendLine($"{indent}if (pos == {preVar}) {fail}");
                    sb.AppendLine($"{indent}value.{fieldName} = {localVar};");
                }
                else
                {
                    sb.AppendLine($"{indent}// ERROR: unregistered type '{typeAlias}'");
                }
            }
            sb.AppendLine();
        }

        // ── 枚举标签扫描方法 ──────────────────────────

        private static string EmitEnumTagMethod(string enumName, List<(string MemberName, string Tag)> tags)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"        /// <summary>枚举标签扫描器：{enumName}</summary>");
            sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"        internal static int Scan_Enum_{enumName}(ReadOnlySpan<char> src, int pos, out {enumName} value)");
            sb.AppendLine("        {");
            sb.AppendLine("            value = default;");
            sb.AppendLine("            if (pos >= src.Length) return pos;");
            sb.AppendLine("            int start = pos;");
            sb.AppendLine("            while (pos < src.Length && char.IsLetter(src[pos])) pos++;");
            sb.AppendLine("            if (pos == start) return start;");
            sb.AppendLine("            switch (new string(src.Slice(start, pos - start)))");
            sb.AppendLine("            {");
            foreach (var (member, tag) in tags)
                sb.AppendLine($"                case \"{tag}\": value = {enumName}.{member}; break;");
            sb.AppendLine("                default: return start;");
            sb.AppendLine("            }");
            sb.AppendLine("            return pos;");
            sb.AppendLine("        }");
            return sb.ToString();
        }

        // ── 重复块 ────────────────────────────────────

        private static int _repCounter;

        private static void EmitRepetitionBlock(
            StringBuilder sb, RepetitionNode rep, string structTypeName,
            Dictionary<string, string> dependencyGraph, string indent)
        {
            if (rep.Body.Count == 0) return;

            int id = _repCounter++;
            string failLabel = $"repFail_{id}";
            string innerIndent = indent + "    ";

            sb.AppendLine($"{indent}// <repetition>");
            sb.AppendLine($"{indent}while (true)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{innerIndent}int saved_{id} = pos;");
            EmitNodeList(sb, rep.Body, structTypeName, dependencyGraph, innerIndent, failLabel);
            sb.AppendLine($"{innerIndent}continue;");
            sb.AppendLine($"{innerIndent}{failLabel}:");
            sb.AppendLine($"{innerIndent}    pos = saved_{id};");
            sb.AppendLine($"{innerIndent}    break;");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine($"{indent}// </repetition>");
            sb.AppendLine();
        }

        private static int _optCounter;

        // ── 可选块 ────────────────────────────────────

        private static void EmitOptionalBlock(
            StringBuilder sb, OptionalBlockNode opt, string structTypeName,
            Dictionary<string, string> dependencyGraph, string indent)
        {
            int id = _optCounter++;
            string skipLabel = $"skipOpt_{id}";
            string endLabel = $"endOpt_{id}";
            string innerIndent = indent + "    ";

            sb.AppendLine($"{indent}// <optional>");
            sb.AppendLine($"{indent}int saved_{id} = pos;");
            sb.AppendLine($"{indent}{{");

            if (opt.Body.Count > 0 && opt.Body[0] is LiteralTextNode firstLit && firstLit.Text.Length <= 6)
            {
                // 有前置字面量：只在前缀匹配时才尝试 body
                string text = firstLit.Text;
                sb.Append($"{innerIndent}if (pos + {text.Length} <= src.Length");
                for (int i = 0; i < text.Length; i++)
                {
                    char c = text[i];
                    string cLit = c == '\'' ? @"'\''" : $"'{c}'";
                    sb.Append($" && src[pos + {i}] == {cLit}");
                }
                sb.AppendLine(")");
                sb.AppendLine($"{innerIndent}{{");
                sb.AppendLine($"{innerIndent}    pos += {text.Length};");
                var rest = GetRest(opt.Body, 1);
                if (rest.Count > 0)
                    EmitNodeList(sb, rest, structTypeName, dependencyGraph, innerIndent + "    ", skipLabel);
                sb.AppendLine($"{innerIndent}    goto {endLabel};");
                sb.AppendLine($"{innerIndent}}}");
            }
            else
            {
                // 无前置字面量：直接尝试 body
                EmitNodeList(sb, opt.Body, structTypeName, dependencyGraph, innerIndent, skipLabel);
                sb.AppendLine($"{innerIndent}goto {endLabel};");
            }

            sb.AppendLine($"{indent}}}");
            sb.AppendLine($"{indent}{skipLabel}:");
            sb.AppendLine($"{indent}    pos = saved_{id};");
            sb.AppendLine($"{indent}{endLabel}:");
            sb.AppendLine($"{indent}// </optional>");
            sb.AppendLine();
        }

        private static List<TemplateNode> GetRest(List<TemplateNode> list, int start)
        {
            var rest = new List<TemplateNode>();
            for (int i = start; i < list.Count; i++)
                rest.Add(list[i]);
            return rest;
        }

        // ── 辅助 ──────────────────────────────────────

        public static string GetScannerMethodName(string structTypeName) => $"Scan_{structTypeName}";

        private static int _varCounter;
        private static string GetUniqueVar(string fieldName) => $"_{fieldName}_{_varCounter++}";

        private static string EscapeForComment(string text)
            => text.Replace("\n", "\\n").Replace("\r", "\\r");
    }
}
