using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text;

namespace SourceSerializer.Generator
{
    [ExcludeFromCodeCoverage]
    internal static class EmitCodeEmitter
    {
        private static readonly HashSet<string> BuiltinTypes = new(StringComparer.OrdinalIgnoreCase)
        {
            "float", "double", "int", "uint", "long", "ulong",
            "short", "ushort", "byte", "sbyte", "bool", "char", "string",
        };

        public static string EmitAll(
            List<(string StructName, List<TemplateNode> Nodes,
                Dictionary<string, FieldInfo> FieldTypes,
                bool NeedsHeapAlloc, bool NeedsWalkPhase, bool IsCollection)> structs,
            Dictionary<string, string> dependencyGraph,
            Dictionary<string, string>? typeAliases = null,
            Dictionary<string, List<(string MemberName, string Tag)>>? enumTagMap = null)
        {
            var tAliases = typeAliases ?? new Dictionary<string, string>();
            var eTags = enumTagMap ?? new Dictionary<string, List<(string, string)>>(StringComparer.Ordinal);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Text;");
            sb.AppendLine();
            sb.AppendLine("namespace SourceSerializer");
            sb.AppendLine("{");
            sb.AppendLine("    partial class SerializerEmitters");
            sb.AppendLine("    {");

            if (structs.Count > 0)
            {
                sb.AppendLine("        static SerializerEmitters()");
                sb.AppendLine("        {");
                foreach (var (name, _, _, _, _, _) in structs)
                {
                    string methodName = GetEmitMethodName(name);
                    sb.AppendLine($"            EmitterRegistry<{name}>.Emitter = (StringBuilder s, {name} v) =>");
                    sb.AppendLine($"            {{");
                    sb.AppendLine($"                {methodName}(s, v);");
                    sb.AppendLine($"            }};");
                }
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            foreach (var (name, nodes, fieldTypes, needsHeapAlloc, needsWalkPhase, isCollection) in structs)
            {
                sb.Append(EmitMethod(name, nodes, isCollection, dependencyGraph, tAliases, eTags, fieldTypes));
                sb.AppendLine();
            }

            foreach (var kv in eTags)
            {
                sb.Append(EmitEnumTagMethod(kv.Key, kv.Value));
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string EmitMethod(
            string structTypeName, List<TemplateNode> nodes, bool isCollection,
            Dictionary<string, string> dependencyGraph,
            Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes)
        {
            var sb = new StringBuilder();
            string methodName = GetEmitMethodName(structTypeName);

            sb.AppendLine($"        /// <summary>序列化器：{structTypeName}</summary>");
            sb.AppendLine("        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"        internal static void {methodName}(StringBuilder sb, {structTypeName} value)");
            sb.AppendLine("        {");

            EmitNodeList(sb, nodes, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, "            ", isCollection: isCollection);

            sb.AppendLine("        }");

            return sb.ToString();
        }

        private static void EmitNodeList(
            StringBuilder sb, List<TemplateNode> nodes, string structTypeName,
            Dictionary<string, string> dependencyGraph, Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes,
            string indent, bool isCollection = false)
        {
            for (int i = 0; i < nodes.Count; i++)
            {
                EmitNode(sb, nodes[i], structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, indent, isCollection);
            }
        }

        private static void EmitNode(
            StringBuilder sb, TemplateNode node, string structTypeName,
            Dictionary<string, string> dependencyGraph, Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes,
            string indent, bool isCollection = false)
        {
            switch (node)
            {
                case LiteralTextNode lit:
                    EmitLiteralText(sb, lit, indent);
                    break;
                case FieldDirectiveNode field:
                    EmitFieldDirective(sb, field, indent, dependencyGraph, typeAliases, enumTags, fieldTypes, isCollection);
                    break;
                case OptionalBlockNode opt:
                    EmitOptionalBlock(sb, opt, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, indent, isCollection);
                    break;
                case RepetitionNode rep:
                    EmitRepetitionStub(sb, rep, indent);
                    break;
            }
        }

        private static void EmitLiteralText(StringBuilder sb, LiteralTextNode lit, string indent)
        {
            string escaped = lit.Text.Replace("\\", "\\\\").Replace("\"", "\\\"");
            sb.AppendLine($"{indent}sb.Append(\"{escaped}\");");
        }

        private static void EmitFieldDirective(
            StringBuilder sb, FieldDirectiveNode field, string indent,
            Dictionary<string, string> dependencyGraph, Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes,
            bool structIsCollection = false)
        {
            string typeAlias = field.TypeAlias;
            string fieldName = field.FieldName;

            string resolvedType = typeAliases.TryGetValue(typeAlias, out var backing)
                ? backing : typeAlias;

            string valueExpr = structIsCollection
                ? "value"
                : $"value.{fieldName}";

            if (BuiltinTypes.Contains(resolvedType))
            {
                string emitMethod = $"Emit_{char.ToUpperInvariant(resolvedType[0])}{resolvedType.Substring(1)}";
                sb.AppendLine($"{indent}SerializerRegistry.{emitMethod}(sb, {valueExpr});");
            }
            else if (enumTags.TryGetValue(typeAlias, out _))
            {
                sb.AppendLine($"{indent}Emit_Enum_{typeAlias}(sb, {valueExpr});");
            }
            else if (dependencyGraph.TryGetValue(typeAlias, out string depMethod))
            {
                string emitDep = depMethod.Replace("Scan_", "Emit_");
                sb.AppendLine($"{indent}{emitDep}(sb, {valueExpr});");
            }
            else
            {
                sb.AppendLine($"{indent}// ERROR: unregistered type '{typeAlias}'");
            }
        }

        private static string EmitEnumTagMethod(string enumName, List<(string MemberName, string Tag)> tags)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"        /// <summary>枚举标签序列化器：{enumName}</summary>");
            sb.AppendLine("        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"        internal static void Emit_Enum_{enumName}(StringBuilder sb, {enumName} value)");
            sb.AppendLine("        {");
            sb.AppendLine($"            switch (value)");
            sb.AppendLine("            {");
            foreach (var (member, tag) in tags)
                sb.AppendLine($"                case {enumName}.{member}: sb.Append(\"{tag}\"); break;");
            sb.AppendLine($"                default: sb.Append(value.ToString()); break;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            return sb.ToString();
        }

        private static void EmitOptionalBlock(
            StringBuilder sb, OptionalBlockNode opt, string structTypeName,
            Dictionary<string, string> dependencyGraph, Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes,
            string indent, bool isCollection = false)
        {
            var optFields = FindOptFields(opt.Body);
            if (optFields.Count == 0)
            {
                EmitNodeList(sb, opt.Body, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, indent, isCollection);
                return;
            }

            var conditions = new List<string>();
            foreach (var f in optFields)
            {
                string valueExpr = isCollection ? "value" : $"value.{f}";
                conditions.Add($"!{valueExpr}.Equals(default({ResolveFieldTypeName(f, fieldTypes)}))");
            }
            string condition = string.Join(" || ", conditions);

            sb.AppendLine($"{indent}if ({condition})");
            sb.AppendLine($"{indent}{{");
            EmitNodeList(sb, opt.Body, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, indent + "    ", isCollection);
            sb.AppendLine($"{indent}}}");
        }

        private static List<string> FindOptFields(List<TemplateNode> nodes)
        {
            var result = new List<string>();
            foreach (var node in nodes)
            {
                if (node is FieldDirectiveNode f)
                    result.Add(f.FieldName);
                else if (node is OptionalBlockNode opt)
                    result.AddRange(FindOptFields(opt.Body));
                else if (node is RepetitionNode rep)
                    result.AddRange(FindOptFields(rep.Body));
            }
            return result;
        }

        private static string ResolveFieldTypeName(string fieldName, Dictionary<string, FieldInfo> fieldTypes)
        {
            if (fieldTypes.TryGetValue(fieldName, out var fi))
            {
                string tn = fi.TypeName;
                if (tn == "System.String" || tn == "string") return "string";
                if (tn == "System.Int32" || tn == "int") return "int";
                if (tn == "System.Single" || tn == "float") return "float";
                if (tn == "System.Double" || tn == "double") return "double";
                if (tn == "System.Boolean" || tn == "bool") return "bool";
                if (tn == "System.Int64" || tn == "long") return "long";
                if (tn == "System.UInt64" || tn == "ulong") return "ulong";
                if (tn == "System.Int16" || tn == "short") return "short";
                if (tn == "System.UInt16" || tn == "ushort") return "ushort";
                if (tn == "System.Byte" || tn == "byte") return "byte";
                if (tn == "System.SByte" || tn == "sbyte") return "sbyte";
                if (tn == "System.Char" || tn == "char") return "char";
                if (tn == "System.UInt32" || tn == "uint") return "uint";
                return tn;
            }
            return fieldName;
        }

        private static void EmitRepetitionStub(StringBuilder sb, RepetitionNode rep, string indent)
        {
            sb.AppendLine($"{indent}// <repetition>: 集合类型序列化延后到 managed 阶段");
        }

        public static string GetEmitMethodName(string structTypeName)
            => "Emit_" + structTypeName.Replace("<", "_").Replace(">", "").Replace(",", "_");
    }
}
