using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text;

namespace SourceSerializer.Generator
{
    [ExcludeFromCodeCoverage]
    internal static class EmitCodeEmitter
    {
        public static string EmitAll(
            List<EmitEntry> structs,
            Dictionary<string, string> dependencyGraph,
            Dictionary<string, string>? typeAliases = null,
            Dictionary<string, List<(string MemberName, string Tag)>>? enumTagMap = null,
            Dictionary<string, List<string>>? interfaceMap = null)
        {
            var tAliases = typeAliases ?? new Dictionary<string, string>();
            var eTags = enumTagMap ?? new Dictionary<string, List<(string, string)>>(StringComparer.Ordinal);
            var iMap = interfaceMap ?? new Dictionary<string, List<string>>(StringComparer.Ordinal);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Text;");
            sb.AppendLine();
            sb.AppendLine("namespace SourceSerializer");
            sb.AppendLine("{");
            sb.AppendLine("    partial class SerializerBlocks");
            sb.AppendLine("    {");

            foreach (var e in structs)
            {
                sb.Append(EmitMethod(e.StructName, e.Nodes, e.IsCollection, dependencyGraph, tAliases, eTags, e.FieldTypes));
                sb.AppendLine();
            }

            foreach (var kv in eTags)
            {
                sb.Append(EmitEnumTagMethod(kv.Key, kv.Value));
                sb.AppendLine();
            }

            // 接口 dispatch 发射方法
            foreach (var kv in iMap)
            {
                sb.Append(EmitInterfaceDispatch(kv.Key, kv.Value, dependencyGraph));
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>为接口生成 dispatch 发射方法：用 switch 模式匹配分发到具体类型的 Emit。</summary>
        private static string EmitInterfaceDispatch(string ifaceName, List<string> concreteTypes,
            Dictionary<string, string> dependencyGraph)
        {
            var sb = new StringBuilder();
            string methodName = GetEmitMethodName(ifaceName);

            sb.AppendLine($"        /// <summary>接口分发序列化器：{ifaceName}</summary>");
            sb.AppendLine($"        internal static void {methodName}(StringBuilder sb, {ifaceName} value)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (value)");
            sb.AppendLine("            {");

            foreach (var concrete in concreteTypes)
            {
                string emitMethod = dependencyGraph.TryGetValue(concrete, out var m)
                    ? m.Replace("Scan_", "Emit_")
                    : GetEmitMethodName(concrete);
                sb.AppendLine($"                case {concrete} v: {emitMethod}(sb, v); break;");
            }

            sb.AppendLine("            }");
            sb.AppendLine("        }");

            return sb.ToString();
        }

        private static string EmitMethod(
            string structTypeName, List<TemplateNode> nodes, bool isCollection,
            Dictionary<string, string> dependencyGraph,
            Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes)
        {
            var sb = new StringBuilder();
            string methodName = GetEmitMethodName(structTypeName);

            sb.AppendLine($"        /// <summary>序列化器：{structTypeName}</summary>");
            sb.AppendLine("        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"        internal static void {methodName}(StringBuilder sb, {structTypeName} value)");
            sb.AppendLine("        {");

            EmitNodeList(sb, nodes, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, "            ", isCollection: isCollection);

            sb.AppendLine("        }");

            return sb.ToString();
        }

        private static void EmitNodeList(
            StringBuilder sb, List<TemplateNode> nodes, string structTypeName,
            Dictionary<string, string> dependencyGraph, Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes,
            string indent, bool isCollection = false, string valueName = "value")
        {
            for (int i = 0; i < nodes.Count; i++)
            {
                EmitNode(sb, nodes[i], structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, indent, isCollection, valueName);
            }
        }

        private static void EmitNode(
            StringBuilder sb, TemplateNode node, string structTypeName,
            Dictionary<string, string> dependencyGraph, Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes,
            string indent, bool isCollection = false, string valueName = "value")
        {
            switch (node)
            {
                case LiteralTextNode lit:
                    EmitLiteralText(sb, lit, indent);
                    break;
                case FieldDirectiveNode field:
                    EmitFieldDirective(sb, field, indent, dependencyGraph, typeAliases, enumTags, fieldTypes, isCollection, valueName);
                    break;
                case OptionalBlockNode opt:
                    EmitOptionalBlock(sb, opt, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, indent, isCollection, valueName);
                    break;
                case RepetitionNode rep:
                    EmitRepetitionBlock(sb, rep, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, indent, isCollection);
                    break;
            }
        }

        private static void EmitLiteralText(StringBuilder sb, LiteralTextNode lit, string indent)
        {
            string escaped = lit.Text.Replace("\\", "\\\\").Replace("\"", "\\\"");
            sb.AppendLine($"{indent}sb.Append(\"{escaped}\");");
        }

        private static void EmitFieldDirective(
            StringBuilder sb, FieldDirectiveNode field, string indent,
            Dictionary<string, string> dependencyGraph, Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes,
            bool structIsCollection = false, string valueName = "value")
        {
            string typeAlias = field.TypeAlias;
            string fieldName = field.FieldName;

            string resolvedType = typeAliases.TryGetValue(typeAlias, out var backing)
                ? backing : typeAlias;

            string valueExpr = structIsCollection
                ? valueName
                : $"{valueName}.@{fieldName}";

            if (BuiltinTypeNames.All.Contains(resolvedType))
            {
                string emitMethod = $"Emit_{char.ToUpperInvariant(resolvedType[0])}{resolvedType.Substring(1)}";
                sb.AppendLine($"{indent}SerializerRegistry.{emitMethod}(sb, {valueExpr});");
            }
            else if (enumTags.TryGetValue(typeAlias, out _))
            {
                sb.AppendLine($"{indent}Emit_Enum_{typeAlias}(sb, {valueExpr});");
            }
            else if (dependencyGraph.TryGetValue(typeAlias, out string depMethod))
            {
                string emitDep = depMethod.Replace("Scan_", "Emit_");
                sb.AppendLine($"{indent}{emitDep}(sb, {valueExpr});");
            }
            else
            {
                sb.AppendLine($"{indent}// ERROR: unregistered type '{typeAlias}'");
            }
        }

        private static string EmitEnumTagMethod(string enumName, List<(string MemberName, string Tag)> tags)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"        /// <summary>枚举标签序列化器：{enumName}</summary>");
            sb.AppendLine("        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"        internal static void Emit_Enum_{enumName}(StringBuilder sb, {enumName} value)");
            sb.AppendLine("        {");
            sb.AppendLine($"            switch (value)");
            sb.AppendLine("            {");
            foreach (var (member, tag) in tags)
                sb.AppendLine($"                case {enumName}.{member}: sb.Append(\"{tag}\"); break;");
            sb.AppendLine($"                default: sb.Append(value.ToString()); break;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            return sb.ToString();
        }

        private static void EmitOptionalBlock(
            StringBuilder sb, OptionalBlockNode opt, string structTypeName,
            Dictionary<string, string> dependencyGraph, Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes,
            string indent, bool isCollection = false, string valueName = "value")
        {
            var optFields = FindOptFields(opt.Body);
            if (optFields.Count == 0)
            {
                EmitNodeList(sb, opt.Body, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, indent, isCollection, valueName);
                return;
            }

            var conditions = new List<string>();
            foreach (var f in optFields)
            {
                string valueExpr = isCollection ? valueName : $"{valueName}.@{f}";
                conditions.Add($"!{valueExpr}.Equals(default({ResolveFieldTypeName(f, fieldTypes)}))");
            }
            string condition = string.Join(" || ", conditions);

            sb.AppendLine($"{indent}if ({condition})");
            sb.AppendLine($"{indent}{{");
            EmitNodeList(sb, opt.Body, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, indent + "    ", isCollection, valueName);
            sb.AppendLine($"{indent}}}");
        }

        private static List<string> FindOptFields(List<TemplateNode> nodes)
        {
            var result = new List<string>();
            foreach (var node in nodes)
            {
                if (node is FieldDirectiveNode f)
                    result.Add(f.FieldName);
                else if (node is OptionalBlockNode opt)
                    result.AddRange(FindOptFields(opt.Body));
                else if (node is RepetitionNode rep)
                    result.AddRange(FindOptFields(rep.Body));
            }
            return result;
        }

        private static string ResolveFieldTypeName(string fieldName, Dictionary<string, FieldInfo> fieldTypes)
        {
            if (fieldTypes.TryGetValue(fieldName, out var fi))
            {
                string tn = fi.TypeName;
                if (tn == "System.String" || tn == "string") return "string";
                if (tn == "System.Int32" || tn == "int") return "int";
                if (tn == "System.Single" || tn == "float") return "float";
                if (tn == "System.Double" || tn == "double") return "double";
                if (tn == "System.Boolean" || tn == "bool") return "bool";
                if (tn == "System.Int64" || tn == "long") return "long";
                if (tn == "System.UInt64" || tn == "ulong") return "ulong";
                if (tn == "System.Int16" || tn == "short") return "short";
                if (tn == "System.UInt16" || tn == "ushort") return "ushort";
                if (tn == "System.Byte" || tn == "byte") return "byte";
                if (tn == "System.SByte" || tn == "sbyte") return "sbyte";
                if (tn == "System.Char" || tn == "char") return "char";
                if (tn == "System.UInt32" || tn == "uint") return "uint";
                return tn;
            }
            return fieldName;
        }

        /// <summary>集合类型序列化：foreach 迭代元素，首元素走 First 模式（无分隔符），后续走 Body 模式。</summary>
        private static void EmitRepetitionBlock(
            StringBuilder sb, RepetitionNode rep, string structTypeName,
            Dictionary<string, string> dependencyGraph, Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes,
            string indent, bool isCollection)
        {
            string itemVar = $"__elem_{_emitVarCounter++}";
            bool hasFirst = rep.First != null;
            string step = indent + "    ";
            // 循环内 body 节点使用 __elem 作为值表达式
            string elemValueName = "__elem";

            if (hasFirst)
            {
                // 首元素：First 模式（无前导分隔符）
                sb.AppendLine($"{indent}// first element");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{step}var {itemVar} = System.Linq.Enumerable.First(value);");
                sb.AppendLine($"{step}var {elemValueName} = {itemVar};");
                EmitNodeList(sb, rep.First!, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, step, isCollection, elemValueName);
                sb.AppendLine($"{indent}}}");

                // 后续元素：Body 模式，foreach 跳过首元素
                sb.AppendLine($"{indent}// remaining elements");
                int flagId = _emitVarCounter++;
                sb.AppendLine($"{indent}bool __first_{flagId} = true;");
                sb.AppendLine($"{indent}foreach (var {itemVar} in value)");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{step}if (__first_{flagId}) {{ __first_{flagId} = false; continue; }}");
                sb.AppendLine($"{step}var {elemValueName} = {itemVar};");
                EmitNodeList(sb, rep.Body, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, step, isCollection, elemValueName);
                sb.AppendLine($"{indent}}}");
            }
            else
            {
                // 无 First：所有元素使用 Body 模式
                sb.AppendLine($"{indent}foreach (var {itemVar} in value)");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{step}var {elemValueName} = {itemVar};");
                EmitNodeList(sb, rep.Body, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, step, isCollection, elemValueName);
                sb.AppendLine($"{indent}}}");
            }
        }

        private static int _emitVarCounter;

        public static string GetEmitMethodName(string structTypeName)
            => "Emit_" + structTypeName.Replace(".", "_").Replace("<", "_").Replace(">", "").Replace(",", "_");
    }
}
