using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;

namespace SourceSerializer.Generator
{
    /// <summary>
    /// 发射策略：控制字段赋值模式（逐字段 vs 构造器）。
    /// </summary>
    internal readonly struct EmitStrategy
    {
        private readonly bool _useConstructor;
        public EmitStrategy(bool useConstructor) => _useConstructor = useConstructor;
        public bool UseConstructor => _useConstructor;
        public string AssignTarget(string fieldName) =>
            _useConstructor ? $"__f_{fieldName}" : $"value.@{fieldName}";
        public string RepetitionTargetPrefix => _useConstructor ? "__f_" : "value.@";
    }

    /// <summary>
    /// 发射器入口：封装一个待生成代码的结构体/类。
    /// </summary>
    internal struct EmitEntry
    {
        public TemplateCommon Common;
        public List<TemplateNode> Nodes;
        public Dictionary<string, FieldInfo> FieldTypes;
    }

    /// <summary>
    /// 将模板 AST 编译为 C# span scanner 源代码。
    /// 生成代码注入到 internal static partial class SerializerBlocks。
    /// </summary>
    // 纯编译期代码发射器，运行时从不实例化
    [ExcludeFromCodeCoverage]
    internal static class ScanCodeEmitter
    {
        /// <summary>
        /// 每次扫描方法生成时的可变状态。由 <see cref="EmitMethod"/> 创建，
        /// 沿调用链显式传递，替代全局 static 字段，消除跨类型状态泄漏。
        /// </summary>
        internal sealed class EmitScanState
        {
            public readonly Dictionary<string, string> HoistedVarMap;
            public readonly Dictionary<string, string> ScanVarMap;
            public int OptCounter;

            public EmitScanState()
            {
                HoistedVarMap = new(StringComparer.Ordinal);
                ScanVarMap = new(StringComparer.Ordinal);
                OptCounter = 0;
            }
        }

        // ═══════════════════════════════════════════════════════
        // 常量
        // ═══════════════════════════════════════════════════════

        /// <summary>内置类型名 → C# 变量类型名（关键字类型用小写，PascalCase 类型用原名）</summary>
        private static readonly Dictionary<string, string> BuiltinCSharpTypeNames = new(StringComparer.OrdinalIgnoreCase)
        {
            ["float"] = "float", ["double"] = "double", ["int"] = "int",
            ["uint"] = "uint", ["long"] = "long", ["ulong"] = "ulong",
            ["short"] = "short", ["ushort"] = "ushort", ["byte"] = "byte",
            ["sbyte"] = "sbyte", ["bool"] = "bool", ["char"] = "char",
            ["string"] = "string",
            ["IntPtr"] = "IntPtr", ["UIntPtr"] = "UIntPtr", ["Guid"] = "Guid",
        };

        /// <summary>顶层方法体单层缩进（12 空格 = 3 层嵌套: class > method > body）</summary>
        private const string IndentTop = "            ";

        /// <summary>子块额外缩进（4 空格）</summary>
        private const string IndentStep = "    ";

        // ═══════════════════════════════════════════════════════
        // 主入口
        // ═══════════════════════════════════════════════════════

        public static string EmitAll(
            List<EmitEntry> structs,
            Dictionary<string, string> dependencyGraph,
            Dictionary<string, string>? typeAliases = null,
            Dictionary<string, List<(string MemberName, string Tag)>>? enumTagMap = null,
            Dictionary<string, List<string>>? interfaceMap = null,
            bool compactWhitespace = false)
        {
            var tAliases = typeAliases ?? new Dictionary<string, string>();
            var eTags = enumTagMap ?? new Dictionary<string, List<(string, string)>>(StringComparer.Ordinal);
            var iMap = interfaceMap ?? new Dictionary<string, List<string>>(StringComparer.Ordinal);

            // 每次 EmitAll 重置所有计数器，确保增量生成输出稳定
            EmitHelpers.ResetCounters();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable CS0162");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine();
            sb.AppendLine("namespace SourceSerializer");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class GeneratedSerializers");
            sb.AppendLine("    {");

            foreach (var e in structs)
            {
                sb.Append(EmitMethod(e.Common.StructName, e.Nodes, e.Common.NeedsHeapAlloc, e.Common.IsCollection, e.Common.IsArrayCollection, e.Common.MatchedCtorParams, dependencyGraph, tAliases, eTags, e.FieldTypes, compactWhitespace));
                sb.AppendLine();
            }

            foreach (var kv in eTags)
            {
                sb.Append(EmitEnumTagMethod(kv.Key, kv.Value));
                sb.AppendLine();
            }

            // 接口 dispatch 方法
            foreach (var kv in iMap)
            {
                sb.Append(EmitInterfaceDispatch(kv.Key, kv.Value, dependencyGraph));
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// 为接口生成 dispatch 扫描方法：按声明顺序尝试，首个推进者胜出。
        /// 模板歧义由 SSR005 在编译期拦截——此处假设所有实现类型模板互不包含。
        /// </summary>
        private static string EmitInterfaceDispatch(string ifaceName, List<string> concreteTypes,
            Dictionary<string, string> dependencyGraph)
        {
            var sb = new StringBuilder();
            string methodName = EmitHelpers.GetMethodName("Scan", ifaceName);

            sb.AppendLine($"        /// <summary>接口分发扫描器：{ifaceName}</summary>");
            sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"        public static int {methodName}(ReadOnlySpan<char> src, int pos, out {ifaceName} value)");
            sb.AppendLine("        {");
            sb.AppendLine("            value = default;");
            sb.AppendLine("            if (pos >= src.Length) return pos;");
            sb.AppendLine("            int start = pos;");
            sb.AppendLine();

            for (int i = 0; i < concreteTypes.Count; i++)
            {
                string concrete = concreteTypes[i];
                string scanMethod = dependencyGraph.TryGetValue(concrete, out var m)
                    ? m : EmitHelpers.GetMethodName("Scan", concrete);
                string localVar = EmitHelpers.GetUniqueVar(concrete);
                string rVar = EmitHelpers.GetUniqueVar("r");

                sb.AppendLine($"            // try {concrete}");
                sb.AppendLine($"            int {rVar} = {scanMethod}(src, pos, out {concrete} {localVar});");
                sb.AppendLine($"            if ({rVar} > pos) {{ value = {localVar}; return {rVar}; }}");
                sb.AppendLine();
            }

            sb.AppendLine("            return start;");
            sb.AppendLine("        }");

            return sb.ToString();
        }

        private static string EmitMethod(
            string structTypeName, List<TemplateNode> nodes, bool needsHeapAlloc, bool isCollection,
            bool isArrayCollection,
            string[]? matchedCtorParams,
            Dictionary<string, string> dependencyGraph,
            Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes,
            bool compactWhitespace = false)
        {
            var sb = new StringBuilder();
            string methodName = EmitHelpers.GetMethodName("Scan",structTypeName);
            // 只有构造器路径才需要延迟构造。readonly struct 无构造器由 GenerateSource 拦截。
            var strategy = new EmitStrategy(matchedCtorParams != null);
            // 每次调用创建新的可变状态，替代跨类型泄漏的 static 字段
            var state = new EmitScanState();

            sb.AppendLine($"        /// <summary>字面量扫描器：{structTypeName}</summary>");
            sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"        public static int {methodName}(ReadOnlySpan<char> src, int pos, out {structTypeName} value)");
            sb.AppendLine("        {");

            if (strategy.UseConstructor)
            {
                sb.AppendLine("            value = default;");
            }
            else
            {
                if (isArrayCollection)
                    sb.AppendLine("            value = null;  // filled by repetition buffer");
                else if (needsHeapAlloc)
                    sb.AppendLine($"            value = new {structTypeName}();");
                else
                    sb.AppendLine("            value = default;");

                // 初始化集合字段为空集合（仅对用户 struct，不处理 synthetic collection 类型）
                if (!isCollection)
                {
                    foreach (var kv in fieldTypes)
                    {
                        if (kv.Value.Kind == CollectionKind.Sequential)
                            sb.AppendLine($"            value.{kv.Key} = {ResolveCollectionType(kv.Value.TypeName, kv.Value.ElemType!)}();");
                        else if (kv.Value.Kind == CollectionKind.Array)
                            sb.AppendLine($"            value.{kv.Key} = System.Array.Empty<{kv.Value.ElemType}>();");
                    }
                }
            }

            sb.AppendLine("            if (pos >= src.Length) return pos;");
            sb.AppendLine("            int start = pos;");
            sb.AppendLine();

            // 顶层 failure mode: 直接 return start
            EmitNodeList(sb, nodes, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, IndentTop, failureLabel: null, isInRepetition: false, isCollection: isCollection, isArrayCollection: isArrayCollection, strategy: strategy, state: state, compactWhitespace: compactWhitespace);

            if (strategy.UseConstructor)
            {
                sb.AppendLine();
                var args = string.Join(", ", matchedCtorParams!.Select(p =>
                {
                    var fld = fieldTypes.Keys.FirstOrDefault(k =>
                        string.Equals(k, p, StringComparison.OrdinalIgnoreCase));
                    return fld != null && state.ScanVarMap.TryGetValue(fld, out var sv) ? sv : "default";
                }));
                sb.AppendLine($"            value = new {structTypeName}({args});");
            }

            sb.AppendLine();
            sb.AppendLine("            return pos;");
            sb.AppendLine("        }");

            return sb.ToString();
        }

        /// <param name="failureLabel">
        /// 失败跳转标签。null 表示顶层（使用 return start），非 null 表示在可选块内（使用 goto failureLabel）
        /// </param>
        private static void EmitNodeList(
            StringBuilder sb, List<TemplateNode> nodes, string structTypeName,
            Dictionary<string, string> dependencyGraph, Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes,
            string indent, string? failureLabel, bool isInRepetition, bool isCollection = false,
            bool isArrayCollection = false,
            EmitStrategy strategy = default,
            EmitScanState? state = null,
            bool compactWhitespace = false)
        {
            for (int i = 0; i < nodes.Count; i++)
            {
                EmitNode(sb, nodes[i], structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, indent, failureLabel, isInRepetition, isCollection, isArrayCollection, strategy, state, compactWhitespace);
            }
        }

        private static void EmitNode(
            StringBuilder sb, TemplateNode node, string structTypeName,
            Dictionary<string, string> dependencyGraph, Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes,
            string indent, string? failureLabel, bool isInRepetition, bool isCollection = false,
            bool isArrayCollection = false,
            EmitStrategy strategy = default,
            EmitScanState? state = null,
            bool compactWhitespace = false)
        {
            switch (node)
            {
                case LiteralTextNode lit:
                    EmitLiteralText(sb, lit, indent, failureLabel, compactWhitespace);
                    break;
                case FieldDirectiveNode field:
                    EmitFieldDirective(sb, field, indent, dependencyGraph, typeAliases, enumTags, fieldTypes, failureLabel, isInRepetition, isCollection, isArrayCollection, strategy, state);
                    break;
                case OptionalBlockNode opt:
                    EmitOptionalBlock(sb, opt, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, indent, isCollection, strategy, state, compactWhitespace);
                    break;
                case RepetitionNode rep:
                    EmitRepetitionBlock(sb, rep, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, indent, isCollection, isArrayCollection, strategy, state, compactWhitespace);
                    break;
                case IndentNode ind:
                    // 缩进标签本身是 no-op，但 body 内的字段仍需扫描
                    EmitNodeList(sb, ind.Body, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, indent, failureLabel, isInRepetition, isCollection, isArrayCollection, strategy, state, compactWhitespace);
                    break;
            }
        }

        private static string MakeFailure(string? failureLabel)
        {
            return failureLabel != null
                ? $"goto {failureLabel};"
                : "return start;";
        }

        // ── 裸文字 ────────────────────────────────────

        private static void EmitLiteralText(StringBuilder sb, LiteralTextNode lit, string indent, string? failureLabel, bool compactWhitespace = false)
        {
            string text = compactWhitespace ? StripWhitespace(lit.Text) : lit.Text;
            if (text.Length == 0) return;
            string fail = MakeFailure(failureLabel);

            sb.AppendLine($"{indent}// literal: {EscapeForComment(text)}");
            sb.AppendLine($"{indent}if (pos + {text.Length} > src.Length) {fail}");

            for (int i = 0; i < text.Length; i++)
            {
                char c = text[i];
                string cLit = c == '\'' ? @"'\''" : $"'{c}'";
                sb.AppendLine($"{indent}if (src[pos + {i}] != {cLit}) {fail}");
            }

            sb.AppendLine($"{indent}pos += {text.Length};");
            sb.AppendLine();
        }

        // ── 字段指令 ──────────────────────────────────

        private static void EmitFieldDirective(
            StringBuilder sb, FieldDirectiveNode field, string indent,
            Dictionary<string, string> dependencyGraph, Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes,
            string? failureLabel, bool isInRepetition, bool structIsCollection = false,
            bool isArrayCollection = false,
            EmitStrategy strategy = default,
            EmitScanState? state = null)
        {
            string typeAlias = field.TypeAlias;
            string fieldName = field.FieldName;
            // 若已在可选块预声明（state.HoistedVarMap），复用已分配的变量名避免重复声明
            string? hoistedVar = null;
            bool isHoisted = state != null && state.HoistedVarMap.TryGetValue(fieldName, out hoistedVar);
            string localVar = isHoisted ? hoistedVar! : EmitHelpers.GetUniqueVar(fieldName);
            string fail = MakeFailure(failureLabel);

            // 别名映射：用户定义的名称 → 实际内置类型
            string resolvedType = typeAliases.TryGetValue(typeAlias, out var backing)
                ? backing : typeAlias;

            // 决定赋值目标: repetition 内的集合字段走数组缓存索引，否则直接写 value.Field
            // 自集合数组类型（如 float[]）也走 buffer——数组不支持 .Add()
            fieldTypes.TryGetValue(fieldName, out var ft);
            bool isCollection = ft.Kind != CollectionKind.None;
            bool useBuffer = (isInRepetition && isCollection)
                || (structIsCollection && isArrayCollection);

            // 构造器路径：记录扫描变量名，跳过中间赋值，末尾直接用扫描变量构造
            bool skipAssign = strategy.UseConstructor && !useBuffer && !structIsCollection;
            if (skipAssign && state != null) state.ScanVarMap[fieldName] = localVar;

            string assignTarget;
            if (useBuffer)
                assignTarget = $"__buf_{fieldName}[__cnt_{fieldName}]";
            else if (structIsCollection)
                assignTarget = "value";
            else
                assignTarget = strategy.AssignTarget(fieldName);
            string assignOp = structIsCollection && !useBuffer
                ? $".Add"
                : " =";
            string assignSuffix = structIsCollection && !useBuffer
                ? $"({localVar});"
                : $" {localVar};";

            // 缓存数组扩容逻辑: 16 → ×4 → 1024 后 ×2
            // 自集合数组类型 fieldTypes 为空，用 typeAlias 作为元素类型
            string resizeElemType = ft.ElemType ?? (isArrayCollection ? typeAlias : null) ?? "object";
            string resizeNewExpr = ArrayNewExpr(resizeElemType, $"__ns_{fieldName}");
            string bufferResize = useBuffer
                ? $"{indent}if (__cnt_{fieldName} >= __buf_{fieldName}.Length)\n{indent}{{\n{indent}    int __ns_{fieldName} = __buf_{fieldName}.Length < 1024 ? __buf_{fieldName}.Length * 4 : __buf_{fieldName}.Length * 2;\n{indent}    var __tmp_{fieldName} = {resizeNewExpr};\n{indent}    Array.Copy(__buf_{fieldName}, __tmp_{fieldName}, __cnt_{fieldName});\n{indent}    __buf_{fieldName} = __tmp_{fieldName};\n{indent}}}\n"
                : "";
            string bufferIncrement = useBuffer
                ? $"{indent}__cnt_{fieldName}++;"
                : "";

            if (BuiltinTypeNames.All.Contains(resolvedType))
            {
                string scannerMethod = $"Scan_{char.ToUpperInvariant(resolvedType[0])}{resolvedType.Substring(1)}";
                string csharpType = BuiltinCSharpTypeNames.TryGetValue(resolvedType, out var ct) ? ct : resolvedType;
                string aliasNote = resolvedType != typeAlias ? $" (alias→{resolvedType})" : "";
                string preVar = EmitHelpers.GetUniqueVar("pre");

                sb.AppendLine($"{indent}// <{typeAlias} {fieldName}>{aliasNote}");
                if (useBuffer) sb.AppendLine(bufferResize);
                sb.AppendLine($"{indent}int {preVar} = pos;");
                string outDecl = isHoisted ? localVar : $"{csharpType} {localVar}";
                sb.AppendLine($"{indent}pos = SerializerRegistry.{scannerMethod}(src, pos, out {outDecl});");
                // 统一 fail 检查：<first> 失败 → 空集合；<body> 失败 → 停止迭代
                sb.AppendLine(isInRepetition && isCollection
                    ? $"{indent}if (pos == {preVar}) {{ /* no progress — empty or done */ {fail}; }}"
                    : $"{indent}if (pos == {preVar}) {fail}");
                if (!skipAssign) sb.AppendLine($"{indent}{assignTarget}{assignOp}{assignSuffix}");
                if (useBuffer) sb.AppendLine(bufferIncrement);
            }
            else if (enumTags.TryGetValue(typeAlias, out var tags))
            {
                string preVar = EmitHelpers.GetUniqueVar("pre");
                sb.AppendLine($"{indent}// <{typeAlias} {fieldName}> (enum tag)");
                if (useBuffer) sb.AppendLine(bufferResize);
                sb.AppendLine($"{indent}int {preVar} = pos;");
                string outDeclET = isHoisted ? localVar : $"{typeAlias} {localVar}";
                sb.AppendLine($"{indent}pos = Scan_Enum_{typeAlias}(src, pos, out {outDeclET});");
                sb.AppendLine($"{indent}if (pos == {preVar}) {fail}");
                if (!skipAssign) sb.AppendLine($"{indent}{assignTarget}{assignOp}{assignSuffix}");
                if (useBuffer) sb.AppendLine(bufferIncrement);
            }
            else
            {
                if (dependencyGraph.TryGetValue(typeAlias, out string depMethod))
                {
                    string preVar = EmitHelpers.GetUniqueVar("pre");
                    sb.AppendLine($"{indent}// <{typeAlias} {fieldName}> (nested)");
                    if (useBuffer) sb.AppendLine(bufferResize);
                    sb.AppendLine($"{indent}int {preVar} = pos;");
                    string outDeclNested = isHoisted ? localVar : $"{typeAlias} {localVar}";
                    sb.AppendLine($"{indent}pos = {depMethod}(src, pos, out {outDeclNested});");
                    sb.AppendLine(isCollection
                        ? $"{indent}// (collection — empty is valid)"
                        : $"{indent}if (pos == {preVar}) {fail}");
                    if (!skipAssign) sb.AppendLine($"{indent}{assignTarget}{assignOp}{assignSuffix}");
                    if (useBuffer) sb.AppendLine(bufferIncrement);
                }
                else
                {
                    sb.AppendLine($"{indent}// ERROR: unregistered type '{typeAlias}'");
                }
            }
            sb.AppendLine();
        }

        // ── 枚举标签扫描方法 ──────────────────────────

        private static string EmitEnumTagMethod(string enumName, List<(string MemberName, string Tag)> tags)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"        /// <summary>枚举标签扫描器：{enumName}</summary>");
            sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"        public static int Scan_Enum_{enumName}(ReadOnlySpan<char> src, int pos, out {enumName} value)");
            sb.AppendLine("        {");
            sb.AppendLine("            value = default;");
            sb.AppendLine("            if (pos >= src.Length) return pos;");
            sb.AppendLine("            int start = pos;");
            sb.AppendLine("            while (pos < src.Length && char.IsLetter(src[pos])) pos++;");
            sb.AppendLine("            if (pos == start) return start;");
            sb.AppendLine("            switch (new string(src.Slice(start, pos - start)))");
            sb.AppendLine("            {");
            foreach (var (member, tag) in tags)
                sb.AppendLine($"                case \"{tag}\": value = {enumName}.{member}; break;");
            sb.AppendLine("                default: return start;");
            sb.AppendLine("            }");
            sb.AppendLine("            return pos;");
            sb.AppendLine("        }");
            return sb.ToString();
        }

        // ── 重复块 ────────────────────────────────────

        private static void EmitRepetitionBlock(
            StringBuilder sb, RepetitionNode rep, string structTypeName,
            Dictionary<string, string> dependencyGraph, Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes,
            string indent, bool isCollection = false, bool isArrayCollection = false,
            EmitStrategy strategy = default,
            EmitScanState? state = null,
            bool compactWhitespace = false)
        {
            if (rep.Body.Count == 0) return;

            int id = EmitHelpers.NextRepId();
            string failLabel = $"repFail_{id}";
            string innerIndent = indent + IndentStep;

            // ── 收集 repetition body 内的集合字段 ──
            var bodyNodes = rep.First!.Concat(rep.Body).ToList();
            var collectionFields = FindCollectionFields(bodyNodes, fieldTypes);

            // ── 自集合数组类型：从模板 AST 提取字段名+元素类型，合成缓冲区 ──
            if (isCollection && isArrayCollection)
            {
                var (fieldName, elemType) = FindElemField(bodyNodes);
                if (fieldName != null)
                    collectionFields.Add((fieldName, elemType));
            }

            sb.AppendLine($"{indent}// <repetition>");

            // ── 循环前: 声明缓存数组 ──
            foreach (var (fieldName, elemType) in collectionFields)
            {
                sb.AppendLine($"{indent}var __buf_{fieldName} = {ArrayNewExpr(elemType, "16")};");
                sb.AppendLine($"{indent}int __cnt_{fieldName} = 0;");
            }

            string savedVar = $"saved_{id}";
            string firstFail = $"repFirstFail_{id}";

            // ── <first>: 首个元素（无分隔符）──
            sb.AppendLine($"{indent}// <first> — try first element (no separator)");
            sb.AppendLine($"{indent}int {savedVar} = pos;");
            sb.AppendLine($"{indent}{{");
            EmitNodeList(sb, rep.First!, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, innerIndent, firstFail, isInRepetition: true, isCollection: isCollection, isArrayCollection: isArrayCollection, state: state, compactWhitespace: compactWhitespace);
            sb.AppendLine($"{innerIndent}goto repLoop_{id};");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine($"{indent}{firstFail}:");
            sb.AppendLine($"{innerIndent}pos = {savedVar};");
            sb.AppendLine($"{innerIndent}goto repEnd_{id};");

            // ── <body>: 后续元素（含分隔符）──
            sb.AppendLine($"{indent}repLoop_{id}: // <body> — subsequent elements");
            sb.AppendLine($"{indent}while (true)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{innerIndent}{savedVar} = pos;");
            EmitNodeList(sb, rep.Body, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, innerIndent, failLabel, isInRepetition: true, isCollection: isCollection, isArrayCollection: isArrayCollection, state: state, compactWhitespace: compactWhitespace);
            sb.AppendLine($"{innerIndent}continue;");
            sb.AppendLine($"{innerIndent}{failLabel}:");
            sb.AppendLine($"{innerIndent}    pos = saved_{id};");
            sb.AppendLine($"{innerIndent}    break;");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine($"{indent}repEnd_{id}: ;");

            // ── 循环后: 缓存数组 → 目标字段单次转换 ──
            string targetPrefix = strategy.RepetitionTargetPrefix;
            foreach (var (fieldName, elemType) in collectionFields)
            {
                // 自集合数组类型：最终化到 value 自身
                string finalNewExpr = ArrayNewExpr(elemType, $"__cnt_{fieldName}");
                if (isArrayCollection)
                {
                    sb.AppendLine($"{indent}value = {finalNewExpr};");
                    sb.AppendLine($"{indent}Array.Copy(__buf_{fieldName}, value, __cnt_{fieldName});");
                    continue;
                }

                var ft = fieldTypes[fieldName];
                if (ft.Kind == CollectionKind.Sequential)
                {
                    sb.AppendLine($"{indent}var __final_{fieldName} = {finalNewExpr};");
                    sb.AppendLine($"{indent}Array.Copy(__buf_{fieldName}, __final_{fieldName}, __cnt_{fieldName});");
                    sb.AppendLine($"{indent}{targetPrefix}{fieldName} = {ResolveCollectionType(ft.TypeName, elemType!)}(__final_{fieldName});");
                }
                else // Array
                {
                    sb.AppendLine($"{indent}var __final_{fieldName} = {finalNewExpr};");
                    sb.AppendLine($"{indent}Array.Copy(__buf_{fieldName}, __final_{fieldName}, __cnt_{fieldName});");
                    sb.AppendLine($"{indent}{targetPrefix}{fieldName} = __final_{fieldName};");
                }
            }

            sb.AppendLine($"{indent}// </repetition>");
            sb.AppendLine();
        }

        /// <summary>从模板节点中提取第一个 FieldDirectiveNode 的 (FieldName, TypeAlias)。</summary>
        private static (string? FieldName, string ElemType) FindElemField(List<TemplateNode> nodes)
        {
            foreach (var node in nodes)
            {
                if (node is FieldDirectiveNode f)
                    return (f.FieldName, f.TypeAlias);
                if (node is OptionalBlockNode opt)
                {
                    var r = FindElemField(opt.Body);
                    if (r.FieldName != null) return r;
                }
                if (node is RepetitionNode rep)
                {
                    var r = FindElemField(rep.Body);
                    if (r.FieldName != null) return r;
                }
            }
            return (null, "")!;
        }

        /// <summary>递归查找节点列表中的集合字段，返回 (fieldName, elementType)</summary>
        private static List<(string FieldName, string ElemType)> FindCollectionFields(
            List<TemplateNode> nodes,
            Dictionary<string, FieldInfo> fieldTypes)
        {
            var result = new List<(string, string)>();
            foreach (var node in nodes)
            {
                if (node is FieldDirectiveNode f)
                {
                    if (fieldTypes.TryGetValue(f.FieldName, out var ft)
                        && ft.Kind != CollectionKind.None
                        && ft.ElemType != null)
                    {
                        bool found = false;
                        for (int j = 0; j < result.Count; j++)
                            if (result[j].Item1 == f.FieldName) { found = true; break; }
                        if (!found)
                            result.Add((f.FieldName, ft.ElemType!));
                    }
                }
                else if (node is OptionalBlockNode opt)
                {
                    var nested = FindCollectionFields(opt.Body, fieldTypes);
                    for (int j = 0; j < nested.Count; j++) result.Add(nested[j]);
                }
                else if (node is RepetitionNode nestedRep)
                {
                    var nested = FindCollectionFields(nestedRep.Body, fieldTypes);
                    for (int j = 0; j < nested.Count; j++) result.Add(nested[j]);
                }
            }
            return result;
        }

        // ── 可选块 ────────────────────────────────────

        private static void EmitOptionalBlock(
            StringBuilder sb, OptionalBlockNode opt, string structTypeName,
            Dictionary<string, string> dependencyGraph, Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags,
            Dictionary<string, FieldInfo> fieldTypes,
            string indent, bool isCollection = false, EmitStrategy strategy = default,
            EmitScanState? state = null,
            bool compactWhitespace = false)
        {
            int id = state != null ? state.OptCounter++ : 0;
            string skipLabel = $"skipOpt_{id}";
            string endLabel = $"endOpt_{id}";
            string innerIndent = indent + IndentStep;

            sb.AppendLine($"{indent}// <optional>");
            sb.AppendLine($"{indent}int saved_{id} = pos;");

            // 构造器策略：预收集可选块内字段并预声明 default，避免 goto skipOpt 跳过声明导致 CS0165
            if (strategy.UseConstructor && state != null)
                EmitHoistedDecls(sb, opt.Body, dependencyGraph, typeAliases, enumTags, indent, state);

            if (opt.Body.Count > 0 && opt.Body[0] is LiteralTextNode firstLit && firstLit.Text.Length <= 6)
            {
                // 有前置字面量：反转条件为提前 goto skip，避免 if { } 作用域包裹 body
                string text = compactWhitespace ? StripWhitespace(firstLit.Text) : firstLit.Text;
                sb.Append($"{innerIndent}if (!(pos + {text.Length} <= src.Length");
                for (int i = 0; i < text.Length; i++)
                {
                    char c = text[i];
                    string cLit = c == '\'' ? @"'\''" : $"'{c}'";
                    sb.Append($" && src[pos + {i}] == {cLit}");
                }
                sb.AppendLine("))");
                sb.AppendLine($"{innerIndent}    goto {skipLabel};");
                sb.AppendLine($"{innerIndent}pos += {text.Length};");
                var rest = GetRest(opt.Body, 1);
                if (rest.Count > 0)
                    EmitNodeList(sb, rest, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, innerIndent, skipLabel, isInRepetition: false, isCollection: isCollection, strategy: strategy, state: state, compactWhitespace: compactWhitespace);
                sb.AppendLine($"{innerIndent}goto {endLabel};");
            }
            else
            {
                // 无前置字面量：直接尝试 body
                EmitNodeList(sb, opt.Body, structTypeName, dependencyGraph, typeAliases, enumTags, fieldTypes, innerIndent, skipLabel, isInRepetition: false, isCollection: isCollection, strategy: strategy, state: state, compactWhitespace: compactWhitespace);
                sb.AppendLine($"{innerIndent}goto {endLabel};");
            }

            sb.AppendLine($"{indent}{skipLabel}:");
            sb.AppendLine($"{indent}    pos = saved_{id};");
            sb.AppendLine($"{indent}{endLabel}:");
            sb.AppendLine($"{indent}// </optional>");
            sb.AppendLine();
        }

        /// <summary>构造器策略：为可选块内字段预声明 Type _name = default; 并登记到 state.HoistedVarMap</summary>
        private static void EmitHoistedDecls(
            StringBuilder sb, List<TemplateNode> body,
            Dictionary<string, string> dependencyGraph, Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags, string indent,
            EmitScanState state)
        {
            var fields = FindFieldDirectives(body);
            foreach (var f in fields)
            {
                string localVar = EmitHelpers.GetUniqueVar(f.FieldName);
                state.HoistedVarMap[f.FieldName] = localVar;
                string csharpType = ResolveCSharpType(f.TypeAlias, dependencyGraph, typeAliases, enumTags);
                sb.AppendLine($"{indent}{csharpType} {localVar} = default;");
            }
        }

        /// <summary>递归查找节点列表中的所有 FieldDirectiveNode</summary>
        private static List<FieldDirectiveNode> FindFieldDirectives(List<TemplateNode> nodes)
        {
            var result = new List<FieldDirectiveNode>();
            foreach (var node in nodes)
            {
                if (node is FieldDirectiveNode f) result.Add(f);
                else if (node is OptionalBlockNode opt) result.AddRange(FindFieldDirectives(opt.Body));
                else if (node is RepetitionNode rep)
                {
                    if (rep.First != null) result.AddRange(FindFieldDirectives(rep.First));
                    result.AddRange(FindFieldDirectives(rep.Body));
                }
            }
            return result;
        }

        /// <summary>将类型别名解析为 C# 类型名（用于变量声明）</summary>
        private static string ResolveCSharpType(
            string typeAlias, Dictionary<string, string> dependencyGraph,
            Dictionary<string, string> typeAliases,
            Dictionary<string, List<(string, string)>> enumTags)
        {
            string resolved = typeAliases.TryGetValue(typeAlias, out var backing) ? backing : typeAlias;
            if (BuiltinTypeNames.All.Contains(resolved))
                return BuiltinCSharpTypeNames.TryGetValue(resolved, out var cst) ? cst : resolved;
            return typeAlias;
        }

        private static List<TemplateNode> GetRest(List<TemplateNode> list, int start)
        {
            var rest = new List<TemplateNode>();
            for (int i = start; i < list.Count; i++)
                rest.Add(list[i]);
            return rest;
        }

        // ── 辅助 ──────────────────────────────────────

        /// <summary>根据字段类型名选择合适的集合构造类型（List vs HashSet）。</summary>
        private static string ResolveCollectionType(string fieldTypeName, string elemType)
        {
            bool isSet = fieldTypeName.StartsWith("HashSet<") ||
                         fieldTypeName.StartsWith("System.Collections.Generic.HashSet<") ||
                         fieldTypeName.StartsWith("ISet<") ||
                         fieldTypeName.StartsWith("System.Collections.Generic.ISet<");
            string collType = isSet ? "System.Collections.Generic.HashSet" : "System.Collections.Generic.List";
            return $"new {collType}<{elemType}>";
        }

        private static string EscapeForComment(string text)
            => text.Replace("\n", "\\n").Replace("\r", "\\r");

        /// <summary>剔除字符串中的所有空白符，用于紧凑模板生成。</summary>
        private static string StripWhitespace(string text)
        {
            if (text.Length == 0) return text;
            // 快速路径：无空白符则直接返回
            bool hasWhitespace = false;
            for (int i = 0; i < text.Length; i++)
            {
                if (char.IsWhiteSpace(text[i])) { hasWhitespace = true; break; }
            }
            if (!hasWhitespace) return text;

            int write = 0;
            char[]? rented = null;
            Span<char> buffer = text.Length <= 256
                ? stackalloc char[256]
                : (rented = System.Buffers.ArrayPool<char>.Shared.Rent(text.Length));
            foreach (char c in text)
                if (!char.IsWhiteSpace(c))
                    buffer[write++] = c;
            string result = buffer.Slice(0, write).ToString();
            if (rented != null) System.Buffers.ArrayPool<char>.Shared.Return(rented);
            return result;
        }

        /// <summary>
        /// 生成数组 new 表达式。若 elemType 本身是数组（如 float[]），
        /// C# 要求 new float[size][] 而非 new float[][size]。
        /// </summary>
        private static string ArrayNewExpr(string elemType, string sizeExpr)
        {
            // 收集末尾的 [] 层级
            int brackets = 0;
            string baseType = elemType;
            while (baseType.EndsWith("[]"))
            {
                brackets++;
                baseType = baseType.Substring(0, baseType.Length - 2);
            }
            // new baseType[size] + 末尾 []...​
            return $"new {baseType}[{sizeExpr}]" + new string('[', brackets) + new string(']', brackets);
        }
    }
}
